        <?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \Magento\ImportExport\Block\Adminhtml\Import\Edit\Before */
?>
<script>
require(['jquery', 'Magento_Ui/js/modal/alert', 'prototype'], function(jQuery){

//<![CDATA[
    // Temporary Class will be replaced after refactoring of import/export functionality
    varienImport.handleEntityTypeSelector = function() {
        var entity = jQuery('#entity');
        if (entity && entity.val()) {
            var entityTo = jQuery('#import_source');
            entityTo.val("");
            varienImport.handleImportSourceSelector();
            this.showBehavior(entity.val());
            this.showImportSource(true);
            this.showSampleFile(entity.val());
        } else {
            this.showBehavior(false);
            this.showImportSource(false);
            this.showSampleFile(false);
        }
    };

    varienImport.handleImportSourceSelector = function() {
        var entity = jQuery('#import_source');
        jQuery('fieldset.source-fieldset').hide();
        jQuery('.source-fieldset').find('._required').removeClass('required-entry').prop('disabled', true);
        if (entity && entity.val()) {
            jQuery('#upload_' + entity.val() + '_fieldset').show();
            jQuery('#upload_' + entity.val() + '_fieldset')
                .find('._required')
                .addClass('required-entry')
                .attr("disabled", false);
        }
    };

    /**
     * Post form data to dynamic iframe.
     * @param {string} newActionUrl OPTIONAL Change form action to this if specified
     */
    varienImport.postToFrame = function(newActionUrl) {
        if (!jQuery('[name="' + this.ifrElemName + '"]').length) {
            jQuery('body').append('<iframe name="' + this.ifrElemName + '" id="' + this.ifrElemName
                + '" style="display:none;"/>');
        }
        jQuery('body')
            .loader({
                icon: jQuery('#loading_mask_loader img').attr('src')
            })
            .loader('show');
        var form = jQuery('#edit_form')
            .one('invalid-form.validate', function(e){jQuery('body').loader('hide')});
        var formAction = newActionUrl ? newActionUrl : form.attr('action');
        newActionUrl = formAction +
            (formAction.lastIndexOf('?') !== -1 ? '&' : '?')+
            'form_key=' + encodeURIComponent(form.find('[name="form_key"]').val());

        form.trigger('save', [{
            action: newActionUrl,
            target: this.ifrElemName
        }]);
    },

    /**
     * Show upload source dropdown
     * @param {boolean} isShow
     */
    varienImport.showImportSource = function(isShow) {
        if (isShow == true) {
            jQuery('#import_source_fieldset').show();
        } else {
            var entity = jQuery('#import_source');
            jQuery('#upload_' + entity.val() + '_fieldset').hide();
            entity.val("");
            jQuery('#import_source_fieldset').hide();
        }
        jQuery('.source-fieldset').find('._required').removeClass('required-entry').prop('disabled', true);
    };
//]]>

});
</script>
