<?php
/**
 * @copyright: Copyright © 2017 Firebear Studio. All rights reserved.
 * @author   : Firebear Studio <fbeardev@gmail.com>
 */
?>
<?php
$items = $block->getItems();
$inc = 1;
?>
<div class="fire_menu">
    <img src="<?php echo $block->getViewFileUrl('Firebear_ImportExport::images/logo.png'); ?>" width="50px"
         height="50px"/>
    Purchase full version of <a target="_blank" href="https://firebearstudio.com/downloadable/customer/products/">Improved Import & Export</a> - scheduled jobs, mapping to support any format, Google Sheet, XML and much more! Full version extension manual |
    <a href="https://firebearstudio.com/contacts" target="_blank">Contact Us</a> for custom import projects or any questions
    <?php
    foreach ($items as $element) :?>
        <a target="_blank" class="<?php /* @escapeNotVerified */
        echo ($inc == 1) ? 'first' : '' ?>" href="<?php /* @escapeNotVerified */
        echo $element['url'] ?>"><?php /* @escapeNotVerified */
            echo $element['label'] ?></a>
        <?php $inc++; ?>
    <?php endforeach; ?>
</div>
